### ISSUE TITLE
GitHub Permissions

### ISSUE THREAD

**Issue by Stebalien** [ipld/team-mgmt#54]
It looks like the main group with write access to this repo is the "contributors" group. In IPFS, at least, that's the catch-all group for everyone that contributes.

1. It might make sense to restrict merge access a bit.
2. It looks like _very_ few members of the IPLD org are in the contributors group. Everyone regularly attending the IPLD meetings should probably have write access to this repo (e.g., @rvagg...).

**Comment by mikeal** [comment]
Thanks @Stebalien, I’m actually in the middle of a permission audit, lots of changes coming soon, I’ll make sure this gets fixed as well.
